name: fading_tile
description: Staggered motion animations for list / grid items.
version: 0.0.2
homepage: https://github.com/volskaya/fading_tile.flutter

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  other_animations: ^0.0.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
